default:
  image: python:3.6

build_and_test:
  variables:
    TEST_PROJECT_NAME: $TEST_PROJECT_NAME
    GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
  cache:
    paths:
      - requirements-dev.txt
    when: 'on_success'
    key: 'build_and_test'
  script:
    - apt-get update -y && apt-get install -y --fix-missing build-essential gfortran
    - python3 -m venv test-venv
    - bash test-venv/bin/activate
    - git clone https://github.com/OpenFAST/python-toolbox.git && pip install -e ./python-toolbox
    - pip install -r requirements-dev.txt
    - coverage run -m unittest
    - coverage report
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'

pages:
  cache:
    paths:
      - docs/requirements.txt
    when: 'on_success'
    key: 'pages'
  script:
  - python3 -m venv docs-venv
  - bash docs-venv/bin/activate
  - pip install -r docs/requirements.txt
  - sphinx-build -b html docs/source public
  artifacts:
    paths:
    - public
  only:
    - master

